// Compiled shader for Web Player, uncompressed size: 6.8KB

// Skipping shader variants that would not be included into build of current scene.

Shader "VertexLit" {
Properties {
 _Opacity ("Opacity", Range(0.01,1)) = 0.7
}
SubShader { 
 Tags { "QUEUE"="Transparent" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 4 math
 //    d3d11_9x : 4 math
 //        d3d9 : 7 math
 // Stats for Fragment shader:
 //        d3d9 : 1 math
 Pass {
  Tags { "QUEUE"="Transparent" "RenderType"="Transparent" }
  GpuProgramID 27799
Program "vp" {
SubProgram "opengl " {
"#version 120

#ifdef VERTEX

varying vec4 xlv_COLOR0;
void main ()
{
  vec4 tmpvar_1;
  tmpvar_1.w = 1.0;
  tmpvar_1.xyz = gl_Vertex.xyz;
  xlv_COLOR0 = clamp (gl_Color, 0.0, 1.0);
  gl_Position = (gl_ModelViewProjectionMatrix * tmpvar_1);
}


#endif
#ifdef FRAGMENT
varying vec4 xlv_COLOR0;
void main ()
{
  gl_FragData[0] = xlv_COLOR0;
}


#endif
"
}
SubProgram "d3d9 " {
// Stats: 7 math
Bind "vertex" Vertex
Bind "color" Color
Matrix 0 [glstate_matrix_mvp]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9431.0
//
// Parameters:
//
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   glstate_matrix_mvp c0       4
//

    vs_2_0
    def c4, 0, 1, 0, 0
    dcl_position v0
    dcl_color v1
    max r0, v1, c4.x
    min oD0, r0, c4.y
    mad r0, v0.xyzx, c4.yyyx, c4.xxxy
    dp4 oPos.x, c0, r0
    dp4 oPos.y, c1, r0
    dp4 oPos.z, c2, r0
    dp4 oPos.w, c3, r0

// approximately 7 instruction slots used
"
}
SubProgram "d3d11 " {
// Stats: 4 math
Bind "vertex" Vertex
Bind "color" Color
ConstBuffer "UnityPerDraw" 352
Matrix 0 [glstate_matrix_mvp]
BindCB  "UnityPerDraw" 0
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// SV_POSITION              0   xyzw        1      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer cb0[4], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyzw
      dcl_output o0.xyzw
      dcl_output_siv o1.xyzw, position
      dcl_temps 1
   0: mov_sat o0.xyzw, v1.xyzw
   1: mul r0.xyzw, v0.yyyy, cb0[1].xyzw
   2: mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
   3: mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
   4: add o1.xyzw, r0.xyzw, cb0[3].xyzw
   5: ret 
// Approximately 0 instruction slots used
"
}
SubProgram "d3d11_9x " {
// Stats: 4 math
Bind "vertex" Vertex
Bind "color" Color
ConstBuffer "UnityPerDraw" 352
Matrix 0 [glstate_matrix_mvp]
BindCB  "UnityPerDraw" 0
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// SV_POSITION              0   xyzw        1      POS   float   xyzw
//
//
// Constant buffer to DX9 shader constant mappings:
//
// Target Reg Buffer  Start Reg # of Regs        Data Conversion
// ---------- ------- --------- --------- ----------------------
// c1         cb0             0         4  ( FLT, FLT, FLT, FLT)
//
//
// Runtime generated constant mappings:
//
// Target Reg                               Constant Description
// ---------- --------------------------------------------------
// c0                              Vertex Shader position offset
//
//
// Level9 shader bytecode:
//
    vs_2_0
          def c5, 0, 1, 0, 0
          dcl_texcoord v0
          dcl_texcoord1 v1
   0:     max r0, v1, c5.x
   1:     min oT0, r0, c5.y
   2:     mul r0, v0.y, c2
   3:     mad r0, c1, v0.x, r0
   4:     mad r0, c3, v0.z, r0
   5:     add r0, r0, c4
   6:     mad oPos.xy, r0.w, c0, r0
   7:     mov oPos.zw, r0

// approximately 8 instruction slots used
      vs_4_0
      dcl_constantbuffer cb0[4], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyzw
      dcl_output o0.xyzw
      dcl_output_siv o1.xyzw, position
      dcl_temps 1
   0: mov_sat o0.xyzw, v1.xyzw
   1: mul r0.xyzw, v0.yyyy, cb0[1].xyzw
   2: mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
   3: mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
   4: add o1.xyzw, r0.xyzw, cb0[3].xyzw
   5: ret 
// Approximately 0 instruction slots used
"
}
}
Program "fp" {
SubProgram "opengl " {
"// shader disassembly not supported on opengl"
}
SubProgram "d3d9 " {
// Stats: 1 math
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9431.0
    ps_2_0
    dcl v0
    mov_pp oC0, v0

// approximately 1 instruction slot used
"
}
SubProgram "d3d11 " {
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// SV_POSITION              0   xyzw        1      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_input_ps linear v0.xyzw
      dcl_output o0.xyzw
   0: mov o0.xyzw, v0.xyzw
   1: ret 
// Approximately 0 instruction slots used
"
}
SubProgram "d3d11_9x " {
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// SV_POSITION              0   xyzw        1      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
//
// Level9 shader bytecode:
//
    ps_2_0
          dcl_pp t0
   0:     mov_pp oC0, t0

// approximately 1 instruction slot used
      ps_4_0
      dcl_input_ps linear v0.xyzw
      dcl_output o0.xyzw
   0: mov o0.xyzw, v0.xyzw
   1: ret 
// Approximately 0 instruction slots used
"
}
}
 }
}
}